### ISSUE TITLE
Debian nfs-kernle-server package ignores /etc/exports.d if /etc/exports does not exist.

### ISSUE THREAD

**Issue by PonderingGrower** [debops/ansible-nfs#4]
Sup,

I just found out that debian `nfs` has a retarded bug that STILL has been not fixed:

https://lists.debian.org/debian-kernel/2012/06/msg00355.html

Apparently a non empty `/etc/exports` has to exist for `nfs` to not ignore files in `/etc/exports.d`.

Could your playbook maybe create `/etc/exports` with nothing but a comment that just mentions this bug?

**Comment by drybjed** [comment]
That's weird, because `/etc/exports` with some comments should be present... Mine for example has:
```
# /etc/exports: the access control list for filesystems which may be exported
#               to NFS clients.  See exports(5).
#
# Example for NFSv2 and NFSv3:
# /srv/homes       hostname1(rw,sync,no_subtree_check) hostname2(ro,sync,no_subtree_check)
#
# Example for NFSv4:
# /srv/nfs4        gss/krb5i(rw,sync,fsid=0,crossmnt,no_subtree_check)
# /srv/nfs4/homes  gss/krb5i(rw,sync,no_subtree_check)
```
And I didn't put that there. Although I've checked in `dpkg` but `/etc/exports` doesn't seem to be a conffile... Can you check if it shows up on a fresh system?

**Comment by PonderingGrower** [comment]
Damn, you are right. After doing `apt-get purge nfs-kernel-server` and then `apt-get install nfs-kernel-server` I did get it recreated:

    Creating config file /etc/exports with new version

I was confused because just running `dpkg-reconfigure nfs-kernel-server` does not recreate the deleted `/etc/exports`. Case closed I guess.

Thanks for the fast reply man, cheers!

**Comment by drybjed** [comment]
Good to hear. :-) I'm closing the issue then.
