### ISSUE TITLE
ansible_local is undefined

### ISSUE THREAD

**Issue by hedii** [debops/ansible-nfs#5]
I had to change nfs_default_path to not mention ansible_local. otherwise i get ansible_local is undefined.
But now, this is debops.ferm role (loaded as a dependency) that outputs the same sort of error:
````
TASK [debops.ferm : Configure ferm status in debconf] **************************
fatal: [111.222.333.444]: FAILED! => {"failed": true, "msg": "'ansible_local' is undefined"}
````

**Comment by drybjed** [comment]
You might want to include [debops.core](https://github.com/debops/ansible-core) role somewhere in the common playbook (doesn't need to be every one, just the one that you use to initialize the host). It creates some of the local Ansible facts needed by other roles to function, and will ensure that `ansible_local` is defined.

**Comment by hedii** [comment]
ok thanks
